from typing import Protocol, Tuple
from src.domain.model.emprestimo import Emprestimo
from src.domain.enums.emprestimo_status import EmprestimoStatus

class EmprestimoRepositoryPort(Protocol):
    def criar(self, emprestimo: Emprestimo) -> Emprestimo: ...
    def listar_paginado(self, page: int, size: int, status: EmprestimoStatus) -> Tuple[list[Emprestimo], int]: ...
    def buscar_ativo_por_livro(self, livro_id: int) -> Emprestimo | None: ...
    def finalizar(self, emprestimo_id: int) -> Emprestimo | None: ...