from typing import Protocol
from src.domain.model.livro import Livro

class LivroRepositoryPort(Protocol):
    def criar(self, livro: Livro) -> Livro: ...
    def listar(self) -> list[Livro]: ...
    def buscar_por_id(self, livro_id: int) -> Livro | None: ...
    def atualizar_disponibilidade(self, livro_id: int, disponivel: bool) -> Livro | None: ...
