from typing import Protocol, Tuple
from src.domain.model.pessoa import Pessoa

class PessoaRepositoryPort(Protocol):
    def criar(self, pessoa: Pessoa) -> Pessoa: ...
    def listar(self) -> list[Pessoa]: ...
    def listar_paginado(self, page: int, size: int) -> Tuple[list[Pessoa], int]: ...
    def buscar_por_id(self, pessoa_id: int) -> Pessoa | None: ...
    def buscar_por_email(self, email: str) -> Pessoa | None: ...
    def email_existe(self, email: str) -> bool: ...
    def atualizar(self, pessoa_id: int, pessoa: Pessoa) -> Pessoa | None: ...
    def remover(self, pessoa_id: int) -> bool: ... 