from typing import Protocol
from sqlalchemy.orm import Session
from src.domain.model.usuario import Usuario

class UsuarioRepositoryPort(Protocol):
    db: Session

    def criar(self, usuario: Usuario) -> Usuario: ...
    def atualizar(self, usuario_id: int, usuario: Usuario) -> Usuario | None: ...
    def remover(self, usuario_id: int) -> bool: ...
    def listar(self) -> list[Usuario]: ...
    def buscar_por_id(self, usuario_id: int) -> Usuario | None: ...
    def buscar_por_email(self, email: str) -> Usuario | None: ... 